version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: cryptomath-captcha-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cryptomath-captcha
      POSTGRES_USER: cryptomath
      POSTGRES_PASSWORD: cryptomath
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cryptomath-captcha-network
  redis:
    image: redis:6.2-alpine
    container_name: cryptomath-captcha-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - cryptomath-captcha-network

volumes:
  postgres-data:
  redis-data:

networks:
  cryptomath-captcha-network:
    driver: bridge